# Generated by Django 2.2.6 on 2019-10-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191101_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.IntegerField(blank=True, default='0', max_length=12),
        ),
    ]
