# Generated by Django 2.2.6 on 2019-10-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='views',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
