# Generated by Django 2.2.6 on 2019-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191101_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PMDC',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
