# Generated by Django 2.2.6 on 2019-11-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_pmdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fee',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
