# Generated by Django 2.2.6 on 2019-11-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191107_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
