# Generated by Django 2.2.6 on 2019-11-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20191107_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='male', max_length=30),
        ),
    ]
