# Generated by Django 2.2.6 on 2019-11-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthzone', '0003_auto_20191108_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='front_page_text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
