# Generated by Django 2.2.6 on 2019-11-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthzone', '0004_blog_front_page_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
