# Generated by Django 2.2.6 on 2019-11-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthzone', '0005_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('front_page_text', models.TextField(blank=True, max_length=500)),
                ('text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='blog')),
            ],
        ),
    ]
