# Generated by Django 2.2.6 on 2019-11-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191104_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='user',
            field=models.IntegerField(),
        ),
    ]
