# Generated by Django 2.2.6 on 2019-11-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191104_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpl',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
