# Generated by Django 2.2.6 on 2019-11-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191104_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPL',
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
        migrations.DeleteModel(
            name='PracticeLocation',
        ),
    ]
