# Generated by Django 2.2.6 on 2019-11-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_doctorpl'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('pl', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('consultation_fee', models.CharField(blank=True, max_length=30)),
                ('postal_address', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
