# Generated by Django 2.2.6 on 2019-11-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191104_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
