# Generated by Django 2.2.6 on 2019-11-05 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_doctorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='pl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='home.PracticeLocation'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PLSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration', models.CharField(max_length=30)),
                ('slot_capacity', models.CharField(max_length=30)),
                ('min_time_before_appointment', models.CharField(max_length=30)),
                ('online_booking', models.BooleanField(default=False)),
                ('future_appointment_days', models.CharField(max_length=30)),
                ('reminder_hours', models.CharField(max_length=30)),
                ('email_notification', models.BooleanField(default=False)),
                ('booking_sms_external', models.BooleanField(default=False)),
                ('booking_sms_internal', models.BooleanField(default=False)),
                ('fee', models.CharField(max_length=30)),
                ('prepayment', models.BooleanField(default=False)),
                ('prepayment_amount', models.CharField(max_length=30)),
                ('prepayment_full_partial', models.BooleanField(default=False)),
                ('show_visit_payment', models.BooleanField(default=False)),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls_pl', to='home.PracticeLocation')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
