# Generated by Django 2.2.6 on 2019-11-06 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_auto_20191105_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plsettings',
            name='booking_sms_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='booking_sms_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='fee',
            field=models.CharField(default='1500', max_length=30),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='future_appointment_days',
            field=models.CharField(default='60', max_length=30),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='min_time_before_appointment',
            field=models.CharField(default='15', max_length=30),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='online_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='prepayment_amount',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='reminder_hours',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='show_visit_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='slot_capacity',
            field=models.CharField(default='2', max_length=30),
        ),
        migrations.AlterField(
            model_name='plsettings',
            name='slot_duration',
            field=models.CharField(default='5', max_length=30),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('patients', models.CharField(max_length=30)),
                ('received', models.DecimalField(decimal_places=10, max_digits=19)),
                ('docotor_share', models.DecimalField(decimal_places=10, max_digits=19)),
                ('hospital_share', models.DecimalField(decimal_places=10, max_digits=19)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
