# Generated by Django 2.2.6 on 2019-11-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191106_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='docotor_share',
            new_name='doctor_share',
        ),
    ]
