# Generated by Django 2.2.6 on 2019-11-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20191106_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='doctor_share',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='hospital_share',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='received',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
