# Generated by Django 2.2.6 on 2019-11-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_docpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
