# Generated by Django 2.2.6 on 2019-11-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20191106_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='patient_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointments',
            name='total_patients',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
