# Generated by Django 2.2.6 on 2019-11-06 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_auto_20191106_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('attachment', models.FileField(upload_to='attachments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userimages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
