# Generated by Django 2.2.6 on 2019-11-08 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_docabout_docawards_docedu_docexp_docpromembership_docservices_docspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpl',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorpl', to=settings.AUTH_USER_MODEL),
        ),
    ]
