# Generated by Django 2.2.6 on 2019-11-09 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20191109_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpl',
            name='pl',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='pl',
        ),
        migrations.AlterField(
            model_name='docedu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docservices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docspec',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docschedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
