# Generated by Django 2.2.6 on 2019-11-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20191110_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpl',
            name='pl',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='home.PracticeLocation'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doc_pl',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='docpl', to='home.DoctorPL'),
        ),
    ]
