# Generated by Django 2.2.6 on 2019-11-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20191110_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='doc_pl',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='pl',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='home.PracticeLocation'),
        ),
        migrations.AlterField(
            model_name='doctorpl',
            name='pl',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
