# Generated by Django 2.2.6 on 2019-11-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20191110_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='pl',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='userid',
        ),
        migrations.DeleteModel(
            name='DoctorPL',
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
