# Generated by Django 2.2.6 on 2019-11-09 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0032_auto_20191110_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.BooleanField(default=False)),
                ('mon', models.BooleanField(default=True)),
                ('tue', models.BooleanField(default=True)),
                ('wed', models.BooleanField(default=True)),
                ('thu', models.BooleanField(default=True)),
                ('fri', models.BooleanField(default=True)),
                ('sat', models.BooleanField(default=False)),
                ('start_time', models.CharField(max_length=30)),
                ('finish_time', models.CharField(max_length=30)),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='home.PracticeLocation')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docschedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('consultation_fee', models.CharField(blank=True, max_length=30)),
                ('postal_address', models.CharField(max_length=30)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorpl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
