# Generated by Django 2.2.6 on 2019-11-10 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20191110_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('otp', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='docabout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docpromembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
