# Generated by Django 2.2.6 on 2019-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20191110_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='pl',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointments',
            name='time',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
