# Generated by Django 2.2.6 on 2019-11-10 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20191110_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='status',
        ),
        migrations.AddField(
            model_name='appointments',
            name='age',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_email',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='appointments',
            name='reason',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='appointments',
            name='service',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='pl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
