# Generated by Django 2.2.6 on 2019-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20191111_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='service',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
