# Generated by Django 2.2.6 on 2019-11-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20191111_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
