# Generated by Django 2.2.6 on 2019-11-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
